# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3068d2e4674cce0e9ec8e0617781f1f8a2b45a56793b3aa765ceb566d989811dc2171ad77b46c3fe9b2799ca7f18c7ca05b2ba58f34b6bba3955d7ea1d573e44

  open_weather_api_key: <%= ENV["OPEN_WEATHER_API_KEY"] %>

test:
  secret_key_base: 0d5bb0e924eae8905edf1d62b60dbb71d68db5a3a00478b69e0e399e0cfbdad1f945fccd2123b8121de1744ab396dad4795263c031375b6feb5e0d925b6e5a26

  open_weather_api_key: <%= ENV["OPEN_WEATHER_API_KEY"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  open_weather_api_key: <%= ENV["OPEN_WEATHER_API_KEY"] %>
